<?php

namespace Database\Seeders;

use App\Models\Designation;
use App\Models\Employee;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $this->call(DesignationSeeder::class);

        $employees = [
            // 0) Charter President & Chief Adviser (Highlighted Founder)
            [
                'employee_id' => 'ROT-9277292',
                'name' => 'Rtn. Chowdhury Md. Hamid Al Mahbub PHF',
                'name_bn' => 'রোটা: চৌধুরী মো: হামিদ আল মাহবুব পিএইচএফ',
                'designation' => 'Chief Adviser & Charter President',
                'phone' => '+8801711001122',
                'email' => 'mahbub.charter@rotaryshantinagardhaka.org',
                'nid_number' => '19602692550000001',
                'present_address' => 'House 14, Road 3, Shanti Nagar, Dhaka',
                'permanent_address' => 'Shanti Nagar, Dhaka-1217',
                'joining_date' => '2017-05-14',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/mahbub.jpg',
                'speech' => '“Rotary is not just an organization; it is a global brotherhood dedicated to selfless humanitarian service. Our mission at Rotary Club of Shantinagar Dhaka is to bring sustainable change, dignity, and empowerment to every marginalized family we touch.”',
                'speech_tag' => 'Charter Philosophy & Visionary Legacy',
                'bio' => 'Charter President (2017-2018), Major Donor & Paul Harris Fellow (PHF). The pioneering founder and visionary behind our club’s humanitarian relief and grassroots community development programs across Bangladesh.',
                'bio_bn' => 'চার্টার সভাপতি (২০১৭-২০১৮), মেজর ডোনার ও পল হ্যারিস ফেলো (PHF)। ক্লাবের প্রতিষ্ঠাতা ও তৃণমূল পর্যায়ে মানবিক সেবামূলক কার্যক্রমের প্রধান পথপ্রদর্শক।',
                'signature_text' => 'Rtn. Chowdhury Md. Hamid Al Mahbub PHF',
                'signature_title' => 'Charter President • Chief Adviser',
                'badge_title' => 'Charter President & Chief Adviser',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 1,
                'is_highlight' => true,
            ],

            // 1) Current President
            [
                'employee_id' => 'ROT-9967283',
                'name' => 'Rtn. Md. Ariful Hoque PHF',
                'name_bn' => 'রোটা: মো: আরিফুল হক পিএইচএফ',
                'designation' => 'President',
                'phone' => '+8801711223344',
                'email' => 'president@rotaryshantinagardhaka.org',
                'nid_number' => '19722692550000002',
                'present_address' => 'Kakrail, Dhaka-1000',
                'permanent_address' => 'Kakrail, Dhaka',
                'joining_date' => '2017-06-20',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/arifulhaque.jpg',
                'speech' => 'Our sacred mission is ensuring no underprivileged family in our community is left without healthcare, clean water, or emergency shelter. At Rotary Club of Shantinagar Dhaka, we turn empathy into permanent, dignity-restoring action across Bangladesh with 100% financial transparency.',
                'speech_tag' => "President's Address & Strategic Vision",
                'bio' => 'Club President and Paul Harris Fellow (PHF). Leading high-impact community service projects, healthcare assistance, and institutional governance across Dhaka District 3281.',
                'bio_bn' => 'ক্লাব সভাপতি ও পল হ্যারিস ফেলো (PHF)। ঢাকা ডিস্ট্রিক্ট ৩২৮১-এর আওতায় বহুমুখী সেবা প্রকল্প, বিনামূল্যে চিকিৎসা এবং প্রাতিষ্ঠানিক সুশাসনে নেতৃত্ব প্রদান করছেন।',
                'signature_text' => 'Rtn. Md. Ariful Hoque PHF',
                'signature_title' => 'President • Rotary Club of Shantinagar Dhaka',
                'badge_title' => 'Club President',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 2,
                'is_highlight' => false,
            ],

            // 2) President Elect / Vice President
            [
                'employee_id' => 'ROT-9967335',
                'name' => 'Rtn. Prof. Dr. Mohammad Shadrul Alam',
                'name_bn' => 'রোটা: অধ্যাপক ডা: মোহাম্মদ শাদরুল আলম',
                'designation' => 'President Elect',
                'phone' => '+8801811556677',
                'email' => 'shadrul.pe@rotaryshantinagardhaka.org',
                'nid_number' => '19742692550000015',
                'present_address' => 'Dhanmondi R/A, Dhaka-1205',
                'permanent_address' => 'Dhaka',
                'joining_date' => '2017-06-20',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/shadrul_alam.jpg',
                'speech' => 'Empowering future generations through specialized medical outreach and accessible education is the cornerstone of sustainable nation building.',
                'speech_tag' => "President Elect's Development Roadmap",
                'bio' => 'President Elect & Senior Vice President. Prominent medical academician directing club health screening camps and hospital equipment donation drives.',
                'bio_bn' => 'নির্বাচিত সভাপতি ও সিনিয়র সহ-সভাপতি। প্রথিতযশা চিকিৎসক ও অধ্যাপক, ফ্রি মেডিকেল ক্যাম্প ও হাসপাতাল সেবা প্রকল্পে বিশেষ ভূমিকা পালন করছেন।',
                'signature_text' => 'Rtn. Prof. Dr. Mohammad Shadrul Alam',
                'signature_title' => 'President Elect • Rotary Club of Shantinagar Dhaka',
                'badge_title' => 'President Elect',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 3,
                'is_highlight' => false,
            ],

            // 3) General Secretary
            [
                'employee_id' => 'ROT-9967301',
                'name' => 'Rtn. Md. Abdus Samad Al Azad PHF',
                'name_bn' => 'রোটা: মো: আব্দুস সামাদ আল আজাদ পিএইচএফ',
                'designation' => 'General Secretary',
                'phone' => '+8801811334455',
                'email' => 'secretary@rotaryshantinagardhaka.org',
                'nid_number' => '19782692550000003',
                'present_address' => 'Shanti Nagar, Dhaka-1217',
                'permanent_address' => 'Shanti Nagar, Dhaka',
                'joining_date' => '2017-06-20',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/samad.jpg',
                'speech' => 'Every single project is executed with direct field verification and rigorous administrative accuracy, leaving zero gap between promise and delivery.',
                'speech_tag' => "General Secretary's Operational Report",
                'bio' => 'General Secretary & Paul Harris Fellow. Managing club administrative correspondence, weekly meeting agendas, RI District reporting, and volunteer mobilization.',
                'bio_bn' => 'সাধারণ সম্পাদক ও পল হ্যারিস ফেলো। ক্লাবের সার্বিক প্রশাসনিক কার্যক্রম, পাক্ষিক সভার আলোচ্যসূচি এবং ডিস্ট্রিক্ট সমন্বয়ের দায়িত্বে নিয়োজিত।',
                'signature_text' => 'Rtn. Md. Abdus Samad Al Azad PHF',
                'signature_title' => 'General Secretary • Rotary Club of Shantinagar Dhaka',
                'badge_title' => 'General Secretary',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 4,
                'is_highlight' => false,
            ],

            // 4) Treasurer & Finance Secretary
            [
                'employee_id' => 'ROT-10089499',
                'name' => 'Rtn. Tasmina Hossain Luna',
                'name_bn' => 'রোটা: তাসমিনা হোসেন লুনা',
                'designation' => 'Treasurer & Finance Secretary',
                'phone' => '+8801911445566',
                'email' => 'treasurer@rotaryshantinagardhaka.org',
                'nid_number' => '19752692550000004',
                'present_address' => 'Bijoy Nagar, Dhaka-1000',
                'permanent_address' => 'Bijoy Nagar, Dhaka',
                'joining_date' => '2018-01-10',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/tasmina.jpg',
                'speech' => 'Every Taka contributed to Rotary Club of Shantinagar Dhaka is managed with itemized vouchers, strict auditing, and total fiscal integrity.',
                'speech_tag' => 'Financial Transparency & Accountability',
                'bio' => 'Club Treasurer overseeing financial ledgers, member dues collections, project budgets, and external regulatory audits.',
                'bio_bn' => 'ক্লাব কোষাধ্যক্ষ হিসেবে সকল আর্থিক হিসাবরক্ষণ, প্রকল্প বাজেট ও স্বচ্ছ নিরীক্ষা নিশ্চিত করেন।',
                'signature_text' => 'Rtn. Tasmina Hossain Luna',
                'signature_title' => 'Treasurer • Rotary Club of Shantinagar Dhaka',
                'badge_title' => 'Treasurer & Finance Secretary',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 5,
                'is_highlight' => false,
            ],

            // 5) Joint Treasurer / Past Secretary
            [
                'employee_id' => 'ROT-10089450',
                'name' => 'Rtn. Md. Pallab Kardar',
                'name_bn' => 'রোটা: মো: পল্লব কারদার',
                'designation' => 'Joint Treasurer',
                'phone' => '+8801718882233',
                'email' => 'pallab.treasury@rotaryshantinagardhaka.org',
                'nid_number' => '19802692550000016',
                'present_address' => 'Malibagh, Dhaka-1217',
                'permanent_address' => 'Malibagh, Dhaka',
                'joining_date' => '2018-05-15',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/pallob.jpg',
                'bio' => 'Joint Treasurer and active executive leader assisting in financial disbursement and club event logistics.',
                'bio_bn' => 'যুগ্ম কোষাধ্যক্ষ ও সক্রিয় রোটারিয়ান, আর্থিক ব্যবস্থাপনা ও ইভেন্ট লজিস্টিকসে গুরুত্বপূর্ণ দায়িত্ব পালন করছেন।',
                'order_index' => 6,
                'is_highlight' => false,
            ],

            // 6) Joint Secretary
            [
                'employee_id' => 'ROT-10129815',
                'name' => 'Rtn. Syeda Salma Jafreen',
                'name_bn' => 'রোটা: সৈয়দা সালমা জাফরিন',
                'designation' => 'Joint Secretary',
                'phone' => '+8801712334455',
                'email' => 'salma.sec@rotaryshantinagardhaka.org',
                'nid_number' => '19822692550000017',
                'present_address' => 'Eskaton Garden, Dhaka-1000',
                'permanent_address' => 'Dhaka',
                'joining_date' => '2019-01-10',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/salma.jpg',
                'bio' => 'Joint Secretary coordinating female membership outreach, social welfare activities, and official minutes of club meetings.',
                'bio_bn' => 'যুগ্ম সম্পাদক হিসেবে ক্লাবের নারী সদস্য সম্পৃক্ততা ও সমাজসেবামূলক মিটিং কার্যবিবরণী তৈরিতে দায়িত্বরত।',
                'order_index' => 7,
                'is_highlight' => false,
            ],

            // 7) Club Trainer
            [
                'employee_id' => 'ROT-10089428',
                'name' => 'Rtn. Archt. Faruk Ahmed',
                'name_bn' => 'রোটা: আর্কিটেক্ট ফারুক আহমেদ',
                'designation' => 'Club Trainer',
                'phone' => '+8801715554433',
                'email' => 'faruk.trainer@rotaryshantinagardhaka.org',
                'nid_number' => '19702692550000018',
                'present_address' => 'Dhanmondi, Dhaka',
                'permanent_address' => 'Dhaka',
                'joining_date' => '2018-07-01',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/faruk_ahmed.png',
                'bio' => 'Club Trainer leading leadership orientation, Rotary ethos workshops, and new member integration.',
                'bio_bn' => 'ক্লাব ট্রেইনার হিসেবে নতুন সদস্যদের রোটারি আদর্শ, নেতৃত্বের গুণাবলী ও সাংগঠনিক প্রশিক্ষণ প্রদান করেন।',
                'order_index' => 8,
                'is_highlight' => false,
            ],

            // 8) Director Club Administration
            [
                'employee_id' => 'ROT-10089418',
                'name' => 'Rtn. Sharmin Akter',
                'name_bn' => 'রোটা: শারমিন আক্তার',
                'designation' => 'Director (Club Administration)',
                'phone' => '+8801817778899',
                'email' => 'sharmin.admin@rotaryshantinagardhaka.org',
                'nid_number' => '19762692550000019',
                'present_address' => 'Shanti Nagar, Dhaka',
                'permanent_address' => 'Dhaka',
                'joining_date' => '2018-09-01',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/sharmin_akter.jpg',
                'bio' => 'Director of Club Administration overseeing club protocol, fellowship events, and attendance records.',
                'bio_bn' => 'পরিচালক (ক্লাব প্রশাসন), ক্লাবের প্রটোকল, ফেলোশিপ ও নিয়মিত উপস্থিতি সংরক্ষণে দায়িত্ব পালন করেন।',
                'order_index' => 9,
                'is_highlight' => false,
            ],

            // 9) Director Membership Development
            [
                'employee_id' => 'ROT-10089414',
                'name' => 'Rtn. Dr. M. Saifur Rahman',
                'name_bn' => 'রোটা: ডা: এম সাইফুর রহমান',
                'designation' => 'Director (Membership Development)',
                'phone' => '+8801918889900',
                'email' => 'saifur.member@rotaryshantinagardhaka.org',
                'nid_number' => '19772692550000020',
                'present_address' => 'Kakrail, Dhaka',
                'permanent_address' => 'Dhaka',
                'joining_date' => '2018-11-01',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/saifur_rahman.png',
                'bio' => 'Director of Membership Development driving new member induction, classification surveys, and engagement.',
                'bio_bn' => 'পরিচালক (সদস্য উন্নয়ন), নতুন সদস্য সংগ্রহ, পরিচিতি পর্ব ও ক্লাবের সম্প্রসারণে নেতৃত্ব দেন।',
                'order_index' => 10,
                'is_highlight' => false,
            ],

            // 10) Director Public Relations
            [
                'employee_id' => 'ROT-10089435',
                'name' => 'Rtn. Rabiul Hasan Joyti',
                'name_bn' => 'রোটা: রবিউল হাসান জ্যোতি',
                'designation' => 'Director (Public Relations & Media)',
                'phone' => '+8801519990011',
                'email' => 'joyti.pr@rotaryshantinagardhaka.org',
                'nid_number' => '19832692550000021',
                'present_address' => 'Motijheel, Dhaka',
                'permanent_address' => 'Dhaka',
                'joining_date' => '2019-02-01',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/robiul_joyti.jpg',
                'bio' => 'Director of Public Relations managing press releases, digital media coverage, and community visibility.',
                'bio_bn' => 'পরিচালক (জনসংযোগ ও প্রচার), ক্লাবের ইতিবাচক ভাবমূর্তি প্রকাশ ও গণমাধ্যমে প্রচারে দায়িত্বরত।',
                'order_index' => 11,
                'is_highlight' => false,
            ],

            // 11) Director Service Projects
            [
                'employee_id' => 'ROT-10089460',
                'name' => 'Rtn. Shah Alam',
                'name_bn' => 'রোটা: শাহ আলম',
                'designation' => 'Director (Service Projects & Relief)',
                'phone' => '+8801712998877',
                'email' => 'shahalam.service@rotaryshantinagardhaka.org',
                'nid_number' => '19792692550000022',
                'present_address' => 'Shanti Nagar, Dhaka',
                'permanent_address' => 'Dhaka',
                'joining_date' => '2019-04-01',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/shah_alam.jpg',
                'bio' => 'Director of Service Projects supervising emergency relief camps, tube-well installations, and school campaigns.',
                'bio_bn' => 'পরিচালক (সেবা প্রকল্প), জরুরি ত্রাণ, আর্সেনিকমুক্ত নলকূপ স্থাপন ও সচেতনতামূলক ক্যাম্পেইন পরিচালনা করেন।',
                'order_index' => 12,
                'is_highlight' => false,
            ],

            // 12) Director The Rotary Foundation (TRF)
            [
                'employee_id' => 'ROT-10089475',
                'name' => 'Rtn. Sinha Abu Khalid PHF',
                'name_bn' => 'রোটা: সিনহা আবু খালেদ পিএইচএফ',
                'designation' => 'Director (The Rotary Foundation - TRF)',
                'phone' => '+8801815667788',
                'email' => 'khalid.trf@rotaryshantinagardhaka.org',
                'nid_number' => '19712692550000023',
                'present_address' => 'Gulshan, Dhaka',
                'permanent_address' => 'Dhaka',
                'joining_date' => '2017-06-20',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/abu_khalid.jpg',
                'bio' => 'Director of TRF fostering Paul Harris Fellow contributions, global grants, and End Polio initiatives.',
                'bio_bn' => 'পরিচালক (TRF), রোটারি ফাউন্ডেশনে সদস্য অনুদান সংগ্রহ ও বৈশ্বিক অনুদান প্রকল্পে কাজ করেন।',
                'order_index' => 13,
                'is_highlight' => false,
            ],

            // 13) Sergeant at Arms
            [
                'employee_id' => 'ROT-10089482',
                'name' => 'Rtn. Mohammad Mahmudul Hasan',
                'name_bn' => 'রোটা: মোহাম্মদ মাহমুদুল হাসান',
                'designation' => 'Sergeant at Arms',
                'phone' => '+8801914332211',
                'email' => 'hasan.saa@rotaryshantinagardhaka.org',
                'nid_number' => '19842692550000024',
                'present_address' => 'Shanti Nagar, Dhaka',
                'permanent_address' => 'Dhaka',
                'joining_date' => '2019-06-01',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/mahmudul_hasan.png',
                'bio' => 'Sergeant at Arms maintaining meeting decorum, fellowship traditions, and club regalia.',
                'bio_bn' => 'সার্জেন্ট অ্যাট আর্মস হিসেবে ক্লাবের শৃঙ্খলারক্ষা, ঐতিহ্য ও আনুষ্ঠানিকতা নিয়ন্ত্রণ করেন।',
                'order_index' => 14,
                'is_highlight' => false,
            ],

            // 14) Additional Directors & Members
            [
                'employee_id' => 'ROT-10914542',
                'name' => 'Rtn. Mumtahina Mostafa',
                'name_bn' => 'রোটা: মুমতাহিনা মোস্তফা',
                'designation' => 'Member (Board of Directors)',
                'phone' => '+8801719998877',
                'email' => 'mumtahina@rotaryshantinagardhaka.org',
                'nid_number' => '19892692550000025',
                'present_address' => 'Shanti Nagar, Dhaka',
                'permanent_address' => 'Dhaka',
                'joining_date' => '2020-01-10',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/mumtahina.jpg',
                'bio' => 'Active Board Member and Joint Sergeant at Arms promoting young leadership and fellowship activities.',
                'bio_bn' => 'বোর্ড মেম্বার ও যুগ্ম সার্জেন্ট অ্যাট আর্মস, তরুণ নেতৃত্ব ও ক্লাব কার্যক্রমে সক্রিয় অংশগ্রহণ করেন।',
                'order_index' => 15,
                'is_highlight' => false,
            ],
            [
                'employee_id' => 'ROT-11278763',
                'name' => 'Rtn. AQM Nasir Uddin',
                'name_bn' => 'রোটা: এ কিউ এম নাসির উদ্দিন',
                'designation' => 'Member (Board of Directors)',
                'phone' => '+8801819998877',
                'email' => 'nasir.editor@rotaryshantinagardhaka.org',
                'nid_number' => '19812692550000026',
                'present_address' => 'Dhaka',
                'permanent_address' => 'Dhaka',
                'joining_date' => '2020-03-15',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/nasir_uddin.jpg',
                'bio' => 'Club Editor in charge of publications, bulletin releases, and project documentation.',
                'bio_bn' => 'ক্লাব সম্পাদক ও বুলেটিন প্রধান, ক্লাবের প্রকাশনা ও নথিপত্র সংরক্ষণে দায়িত্ব পালন করেন।',
                'order_index' => 16,
                'is_highlight' => false,
            ],

            // 15) Ground Operations & Office Staff
            [
                'employee_id' => 'EMP-001',
                'name' => 'Rtn. Md. Saifullah Russell',
                'name_bn' => 'রোটা: মো: সাইফুল্লাহ রাসেল',
                'designation' => 'Field Project Coordinator',
                'phone' => '+8801712998811',
                'email' => 'russel.field@rotaryshantinagardhaka.org',
                'nid_number' => '19852692550000009',
                'present_address' => 'Shanti Nagar, Dhaka-1217',
                'permanent_address' => 'Shanti Nagar, Dhaka',
                'joining_date' => '2021-06-01',
                'base_salary' => 35000.00,
                'is_active' => true,
                'photo' => 'assets/images/team/saifullah_russel.jpg',
                'bio' => 'Executing on-ground logistics, beneficiary verification, and daily relief deliveries.',
                'bio_bn' => 'মাঠপর্যায়ে সহায়তা বিতরণ ও উপকারভোগীদের তথ্য সরেজমিনে যাচাইয়ের দায়িত্ব পালন করেন।',
                'order_index' => 17,
                'is_highlight' => false,
            ],
            [
                'employee_id' => 'EMP-002',
                'name' => 'Rtn. Wahiba Akhter PHF',
                'name_bn' => 'রোটা: ওয়াহিবা আক্তার পিএইচএফ',
                'designation' => 'Accounts & Documentation Officer',
                'phone' => '+8801815667722',
                'email' => 'wahiba.acc@rotaryshantinagardhaka.org',
                'nid_number' => '19882692550000010',
                'present_address' => 'Malibagh, Dhaka-1217',
                'permanent_address' => 'Malibagh, Dhaka',
                'joining_date' => '2021-09-01',
                'base_salary' => 30000.00,
                'is_active' => true,
                'photo' => 'assets/images/team/wahiba_akhter.jpg',
                'bio' => 'Maintaining money receipt logs, itemized debit vouchers, and internal financial records.',
                'bio_bn' => 'দৈনন্দিন অনুদানের মানি রসিদ, খরচের ভাউচার এবং আর্থিক হিসাব সংরক্ষণ করেন।',
                'order_index' => 18,
                'is_highlight' => false,
            ],
            [
                'employee_id' => 'EMP-003',
                'name' => 'Rtn. Sankar Das',
                'name_bn' => 'রোটা: শংকর দাস',
                'designation' => 'Volunteer Supervisor & Logistics Support',
                'phone' => '+8801914332233',
                'email' => 'sankar.volunteer@rotaryshantinagardhaka.org',
                'nid_number' => '19902692550000011',
                'present_address' => 'Shanti Nagar, Dhaka-1217',
                'permanent_address' => 'Shanti Nagar, Dhaka',
                'joining_date' => '2022-01-01',
                'base_salary' => 25000.00,
                'is_active' => true,
                'photo' => 'assets/images/team/sankar_das.jpg',
                'bio' => 'Managing youth volunteer teams and coordinating medical distribution camps.',
                'bio_bn' => 'স্বেচ্ছাসেবক টিমের সার্বিক পরিচালনা ও ত্রাণ বিতরণ ক্যাম্প সমন্বয় করেন।',
                'order_index' => 19,
                'is_highlight' => false,
            ],
            [
                'employee_id' => 'EMP-004',
                'name' => 'Rtn. Hamidul Haque Khan',
                'name_bn' => 'রোটা: হামিদুল হক খান',
                'designation' => 'Office Caretaker & Logistics Assistant',
                'phone' => '+8801611009944',
                'email' => 'hamidul.support@rotaryshantinagardhaka.org',
                'nid_number' => '19922692550000012',
                'present_address' => 'Staff Quarters, Dhaka',
                'permanent_address' => 'Dhaka',
                'joining_date' => '2022-04-01',
                'base_salary' => 18000.00,
                'is_active' => true,
                'photo' => 'assets/images/team/hamidul_haque.jpg',
                'bio' => 'Handling office maintenance and physical relief material loading.',
                'bio_bn' => 'কার্যালয় রক্ষণাবেক্ষণ ও ত্রাণ সামগ্রী লোডিং-আনলোডিংয়ে সহায়তা করেন।',
                'order_index' => 20,
                'is_highlight' => false,
            ],
        ];

        foreach ($employees as $data) {
            $designationName = $data['designation'];
            unset($data['designation']);

            $desig = Designation::where('name', $designationName)->first();
            $data['designation_id'] = $desig?->id;

            Employee::updateOrCreate(
                ['employee_id' => $data['employee_id']],
                $data
            );
        }
    }
}
