<?php

namespace Database\Seeders;

use App\Models\Designation;
use App\Models\Employee;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $this->call(DesignationSeeder::class);
        $employees = [
            // 0) Highlight for Best President Ever
            [
                'employee_id' => 'EMP-001',
                'name' => 'Alhaj Mohammad Nurul Islam',
                'name_bn' => 'আলহাজ্ব মোহাম্মদ নুরুল ইসলাম',
                'designation' => 'President',
                'phone' => '+8801711001122',
                'email' => 'patron@shantinagarfoundation.org',
                'nid_number' => '19602692550000001',
                'present_address' => 'House 14, Road 3, Shanti Nagar, Dhaka',
                'permanent_address' => 'Shanti Nagar, Dhaka-1217',
                'joining_date' => '2015-01-01',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-9.jpg',
                'speech' => '“A true humanitarian mission is not measured by the size of donations, but by the purity of transparency and the dignity restored to every vulnerable life we touch.”',
                'speech_tag' => 'Lifetime Humanitarian Philosophy',
                'bio' => 'Recognized as the foundational cornerstone and most beloved leader of Rotary Club of Shantinagar Dhaka. Under his visionary stewardship, our grassroots relief initiatives reached over 50,000 underprivileged families with 100% itemized audit transparency and direct field procurement.',
                'bio_bn' => 'রোটারি ক্লাব অব শান্তিনগর ঢাকার স্বপ্নদ্রষ্টা ও আজীবন পৃষ্ঠপোষক। তাঁর দূরদর্শী নেতৃত্বে আমাদের মানবিক সেবামূলক কাজ ৫০,০০০-এরও বেশি পরিবারের কাছে সরাসরি পৌঁছেছে।',
                'signature_text' => 'Alhaj Mohammad Nurul Islam',
                'signature_title' => 'Founding Pillar • Lifetime Patron',
                'badge_title' => 'Honorary Tribute • Lifetime Patron',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 1,
                'is_highlight' => true,
            ],

            // 1) President
            [
                'employee_id' => 'EMP-002',
                'name' => 'Advocate Mahfuzur Rahman',
                'name_bn' => 'এডভোকেট মাহফুজুর রহমান',
                'designation' => 'President',
                'phone' => '+8801711223344',
                'email' => 'president@shantinagarfoundation.org',
                'nid_number' => '19722692550000002',
                'present_address' => 'Kakrail, Dhaka-1000',
                'permanent_address' => 'Kakrail, Dhaka',
                'joining_date' => '2018-03-01',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-5.jpg',
                'speech' => 'Our sacred mission is ensuring no underprivileged family in our community is left without healthcare, clean water, or emergency shelter. At Rotary Club of Shantinagar Dhaka, we believe true leadership is rooted in selfless service. By uniting generous benefactors with verified grassroots programs, we turn empathy into permanent, dignity-restoring action across Bangladesh.',
                'speech_tag' => "President's Address & Vision",
                'bio' => 'Serving as President with a focus on institutional governance, legal compliance, and strategic grassroots outreach across Bangladesh.',
                'bio_bn' => 'সভাপতি হিসেবে তিনি প্রশাসনিক স্বচ্ছতা, প্রাতিষ্ঠানিক সুশাসন ও তৃণমূল সেবামূলক কার্যক্রমে নেতৃত্ব দিয়ে আসছেন।',
                'signature_text' => 'Advocate Mahfuzur Rahman',
                'signature_title' => 'President • Rotary Club of Shantinagar Dhaka',
                'badge_title' => 'President',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 2,
                'is_highlight' => false,
            ],

            // 2) General Secretary
            [
                'employee_id' => 'EMP-003',
                'name' => 'Dr. Tariqul Islam',
                'name_bn' => 'ডা: তরিকুল ইসলাম',
                'designation' => 'General Secretary',
                'phone' => '+8801811334455',
                'email' => 'secretary@shantinagarfoundation.org',
                'nid_number' => '19782692550000003',
                'present_address' => 'Shanti Nagar, Dhaka-1217',
                'permanent_address' => 'Shanti Nagar, Dhaka',
                'joining_date' => '2019-01-15',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-6.jpg',
                'speech' => 'Every single project is managed with 100% internal audit transparency and direct field verification. We leave zero room for intermediaries.',
                'speech_tag' => "General Secretary's Report",
                'bio' => 'Coordinating day-to-day relief administration, volunteer brigades, medical drives, and transparent field operations.',
                'bio_bn' => 'প্রতিদিনের ত্রাণ বিতরণ, স্বেচ্ছাসেবী টিম ও স্বাস্থ্য ক্যাম্পের সফল সমন্বয় সাধন করেন।',
                'signature_text' => 'Dr. Tariqul Islam',
                'signature_title' => 'General Secretary • Rotary Club of Shantinagar Dhaka',
                'badge_title' => 'General Secretary',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 3,
                'is_highlight' => false,
            ],

            // 3) Treasurer & Finance Secretary
            [
                'employee_id' => 'EMP-004',
                'name' => 'Engr. Shahabuddin Ahmed',
                'name_bn' => 'প্রকৌশলী শাহাবুদ্দিন আহমেদ',
                'designation' => 'Treasurer & Finance Secretary',
                'phone' => '+8801911445566',
                'email' => 'treasurer@shantinagarfoundation.org',
                'nid_number' => '19752692550000004',
                'present_address' => 'Bijoy Nagar, Dhaka-1000',
                'permanent_address' => 'Bijoy Nagar, Dhaka',
                'joining_date' => '2019-06-01',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-7.jpg',
                'speech' => 'Every Taka donated to Rotary Club of Shantinagar Dhaka is fully audited and mapped directly to concrete relief deliverables with itemized vouchers.',
                'speech_tag' => 'Financial Transparency Commitment',
                'bio' => 'Managing accounting systems, financial integrity, donation voucher audits, and regulatory reporting.',
                'bio_bn' => 'আর্থিক স্বচ্ছতা ও প্রতিটি ব্যয়ের পুঙ্খানুপুঙ্খ হিসাব সংরক্ষণের দায়িত্ব পালন করেন।',
                'signature_text' => 'Engr. Shahabuddin Ahmed',
                'signature_title' => 'Treasurer • Rotary Club of Shantinagar Dhaka',
                'badge_title' => 'Treasurer & Finance Secretary',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 4,
                'is_highlight' => false,
            ],

            // 4) Board of Directors (BOD)
            [
                'employee_id' => 'EMP-005',
                'name' => 'Mohammad Anwarul Kabir',
                'name_bn' => 'মোহাম্মদ আনোয়ারুল কবির',
                'designation' => 'Director (Relief Operations)',
                'phone' => '+8801715556677',
                'email' => 'anwar.bod@shantinagarfoundation.org',
                'nid_number' => '19702692550000005',
                'present_address' => 'House 12, Road 4, Shanti Nagar, Dhaka',
                'permanent_address' => 'Shanti Nagar, Dhaka',
                'joining_date' => '2019-08-01',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-8.jpg',
                'bio' => 'Supervising emergency relief procurement and rapid field mobilization across flood and disaster prone districts.',
                'bio_bn' => 'বন্যা ও দুর্যোগকবলিত জেলাসমূহে জরুরি ত্রাণ সংগ্রহ ও তাৎক্ষণিক মাঠপর্যায়ে বিতরণের সার্বিক তত্ত্বাবধান করেন।',
                'order_index' => 5,
                'is_highlight' => false,
            ],
            [
                'employee_id' => 'EMP-006',
                'name' => 'Begum Rashida Akhtar',
                'name_bn' => 'বেগম রাশিদা আক্তার',
                'designation' => 'Director (Social Welfare & Orphan Care)',
                'phone' => '+8801817778899',
                'email' => 'rashida.bod@shantinagarfoundation.org',
                'nid_number' => '19742692550000006',
                'present_address' => 'Eskaton Garden, Dhaka-1000',
                'permanent_address' => 'Eskaton, Dhaka',
                'joining_date' => '2020-01-10',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-2.jpg',
                'bio' => 'Guiding educational sponsorship for orphaned students and livelihood kits for distressed single mothers.',
                'bio_bn' => 'এতিম শিশুদের শিক্ষা বৃত্তি ও অসহায় নারীদের স্বাবলম্বীকরণ কার্যক্রমে নেতৃত্ব দেন।',
                'order_index' => 6,
                'is_highlight' => false,
            ],
            [
                'employee_id' => 'EMP-007',
                'name' => 'Dr. Masudur Rahman',
                'name_bn' => 'ডা: মাসুদুর রহমান',
                'designation' => 'Director (Medical Aid & Healthcare)',
                'phone' => '+8801918889900',
                'email' => 'masud.bod@shantinagarfoundation.org',
                'nid_number' => '19762692550000007',
                'present_address' => 'Kakrail, Dhaka-1000',
                'permanent_address' => 'Kakrail, Dhaka',
                'joining_date' => '2020-05-01',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-3.jpg',
                'bio' => 'Overseeing public hospital equipment donations, free medical camps, and patient assistance programs.',
                'bio_bn' => 'সরকারি হাসপাতালে চিকিৎসা সরঞ্জাম অনুদান, ফ্রি মেডিকেল ক্যাম্প ও জরুরি রোগী সহায়তা কার্যক্রম পরিচালনা করেন।',
                'order_index' => 7,
                'is_highlight' => false,
            ],
            [
                'employee_id' => 'EMP-008',
                'name' => 'Farhana Yasmin',
                'name_bn' => 'ফারহানা ইয়াসমিন',
                'designation' => 'Director (Women Empowerment & Education)',
                'phone' => '+8801519990011',
                'email' => 'farhana.bod@shantinagarfoundation.org',
                'nid_number' => '19822692550000008',
                'present_address' => 'Dhanmondi R/A, Dhaka-1209',
                'permanent_address' => 'Dhanmondi, Dhaka',
                'joining_date' => '2021-02-15',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-4.jpg',
                'bio' => 'Leading women skill development centers and adult literacy programs in urban slums.',
                'bio_bn' => 'বস্তিবাসীদের জন্য নারী দক্ষতা উন্নয়ন কেন্দ্র ও বয়স্ক শিক্ষা কর্মসূচি পরিচালনা করেন।',
                'order_index' => 8,
                'is_highlight' => false,
            ],

            // 5) Foundation Officers & Coordinators
            [
                'employee_id' => 'EMP-009',
                'name' => 'Rafiqul Islam',
                'name_bn' => 'রফিকুল ইসলাম',
                'designation' => 'Field Project Coordinator',
                'phone' => '+8801712998877',
                'email' => 'rafiq.field@shantinagarfoundation.org',
                'nid_number' => '19852692550000009',
                'present_address' => 'Shanti Nagar, Dhaka-1217',
                'permanent_address' => 'Shanti Nagar, Dhaka',
                'joining_date' => '2021-06-01',
                'base_salary' => 35000.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-1.jpg',
                'bio' => 'Executing on-ground logistics, beneficiary verification, and daily relief deliveries.',
                'bio_bn' => 'মাঠপর্যায়ে সহায়তা বিতরণ ও উপকারভোগীদের তথ্য সরেজমিনে যাচাইয়ের দায়িত্ব পালন করেন।',
                'order_index' => 9,
                'is_highlight' => false,
            ],
            [
                'employee_id' => 'EMP-010',
                'name' => 'Fatema Begum',
                'name_bn' => 'ফাতেমা বেগম',
                'designation' => 'Accounts & Documentation Officer',
                'phone' => '+8801815667788',
                'email' => 'fatema.acc@shantinagarfoundation.org',
                'nid_number' => '19882692550000010',
                'present_address' => 'Malibagh, Dhaka-1217',
                'permanent_address' => 'Malibagh, Dhaka',
                'joining_date' => '2021-09-01',
                'base_salary' => 30000.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-2.jpg',
                'bio' => 'Maintaining money receipt logs, itemized debit vouchers, and internal financial records.',
                'bio_bn' => 'দৈনন্দিন অনুদানের মানি রসিদ, খরচের ভাউচার এবং আর্থিক হিসাব সংরক্ষণ করেন।',
                'order_index' => 10,
                'is_highlight' => false,
            ],
            [
                'employee_id' => 'EMP-011',
                'name' => 'Kamrul Hasan',
                'name_bn' => 'কামরুল হাসান',
                'designation' => 'Volunteer Supervisor & Logistics Support',
                'phone' => '+8801914332211',
                'email' => 'kamrul.volunteer@shantinagarfoundation.org',
                'nid_number' => '19902692550000011',
                'present_address' => 'Shanti Nagar, Dhaka-1217',
                'permanent_address' => 'Shanti Nagar, Dhaka',
                'joining_date' => '2022-01-01',
                'base_salary' => 25000.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-3.jpg',
                'bio' => 'Managing youth volunteer teams and coordinating medical distribution camps.',
                'bio_bn' => 'স্বেচ্ছাসেবক টিমের সার্বিক পরিচালনা ও ত্রাণ বিতরণ ক্যাম্প সমন্বয় করেন।',
                'order_index' => 11,
                'is_highlight' => false,
            ],
            [
                'employee_id' => 'EMP-012',
                'name' => 'Abdul Kader',
                'name_bn' => 'আব্দুল কাদের',
                'designation' => 'Office Caretaker & Logistics Assistant',
                'phone' => '+8801611009988',
                'email' => 'kader.support@shantinagarfoundation.org',
                'nid_number' => '19922692550000012',
                'present_address' => 'Staff Quarters, Dhaka',
                'permanent_address' => 'Dhaka',
                'joining_date' => '2022-04-01',
                'base_salary' => 18000.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-4.jpg',
                'bio' => 'Handling office maintenance and physical relief material loading.',
                'bio_bn' => 'কার্যালয় রক্ষণাবেক্ষণ ও ত্রাণ সামগ্রী লোডিং-আনলোডিংয়ে সহায়তা করেন।',
                'order_index' => 12,
                'is_highlight' => false,
            ],
        ];

        foreach ($employees as $data) {
            $designationName = $data['designation'];
            unset($data['designation']);

            $desig = Designation::where('name', $designationName)->first();
            $data['designation_id'] = $desig?->id;

            Employee::updateOrCreate(
                ['employee_id' => $data['employee_id']],
                $data
            );
        }
    }
}
