<?php

namespace Database\Seeders;

use App\Models\Designation;
use App\Models\Employee;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $this->call(DesignationSeeder::class);
        $employees = [
            // 0) Highlight for Best President Ever
            [
                'employee_id' => 'EMP-001',
                'name' => 'Alhaj Mohammad Nurul Islam',
                'designation' => 'President',
                'phone' => '+8801711001122',
                'email' => 'patron@shantinagarfoundation.org',
                'nid_number' => '19602692550000001',
                'present_address' => 'House 14, Road 3, Shanti Nagar, Dhaka',
                'permanent_address' => 'Shanti Nagar, Dhaka-1217',
                'joining_date' => '2015-01-01',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-9.jpg',
                'speech' => '“A true humanitarian mission is not measured by the size of donations, but by the purity of transparency and the dignity restored to every vulnerable life we touch.”',
                'speech_tag' => 'Lifetime Humanitarian Philosophy',
                'bio' => 'Recognized as the foundational cornerstone and most beloved leader of Rotary Club of Shantinagar Dhaka. Under his visionary stewardship, our grassroots relief initiatives reached over 50,000 underprivileged families with 100% itemized audit transparency and direct field procurement.',
                'signature_text' => 'Alhaj Mohammad Nurul Islam',
                'signature_title' => 'Founding Pillar • Lifetime Patron',
                'badge_title' => 'Honorary Tribute • Lifetime Patron',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 1,
                'is_highlight' => true,
            ],

            // 1) President
            [
                'employee_id' => 'EMP-002',
                'name' => 'Advocate Mahfuzur Rahman',
                'designation' => 'President',
                'phone' => '+8801711223344',
                'email' => 'president@shantinagarfoundation.org',
                'nid_number' => '19722692550000002',
                'present_address' => 'Kakrail, Dhaka-1000',
                'permanent_address' => 'Kakrail, Dhaka',
                'joining_date' => '2018-03-01',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-5.jpg',
                'speech' => 'Our sacred mission is ensuring no underprivileged family in our community is left without healthcare, clean water, or emergency shelter. At Rotary Club of Shantinagar Dhaka, we believe true leadership is rooted in selfless service. By uniting generous benefactors with verified grassroots programs, we turn empathy into permanent, dignity-restoring action across Bangladesh.',
                'speech_tag' => "President's Address & Vision",
                'bio' => 'Serving as President with a focus on institutional governance, legal compliance, and strategic grassroots outreach across Bangladesh.',
                'signature_text' => 'Advocate Mahfuzur Rahman',
                'signature_title' => 'President • Rotary Club of Shantinagar Dhaka',
                'badge_title' => 'President',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 2,
            ],

            // 2) Secretary
            [
                'employee_id' => 'EMP-003',
                'name' => 'Dr. Kazi Ashraful Alam',
                'designation' => 'General Secretary',
                'phone' => '+8801712334455',
                'email' => 'secretary@shantinagarfoundation.org',
                'nid_number' => '19782692550000003',
                'present_address' => 'Shanti Nagar, Dhaka-1217',
                'permanent_address' => 'Brahmanbaria Sadar, Brahmanbaria',
                'joining_date' => '2018-03-01',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-6.jpg',
                'speech' => 'Unwavering transparency, rapid disaster mobilization, and grounded field execution define our operational ethos. Every project is meticulously planned, vetted, and executed with our dedicated volunteer force to ensure immediate and direct relief to those facing hardship.',
                'speech_tag' => "General Secretary's Statement",
                'bio' => 'Oversees daily field operations, rapid disaster response squads, and volunteer coordination nationwide.',
                'signature_text' => 'Dr. Kazi Ashraful Alam',
                'signature_title' => 'General Secretary • Rotary Club of Shantinagar Dhaka',
                'badge_title' => 'General Secretary',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 3,
            ],

            // 3) Treasurer
            [
                'employee_id' => 'EMP-004',
                'name' => 'Engr. Shahadat Hossain',
                'designation' => 'Treasurer & Finance Secretary',
                'phone' => '+8801713445566',
                'email' => 'treasurer@shantinagarfoundation.org',
                'nid_number' => '19802692550000004',
                'present_address' => 'Malibagh Chowdhury Para, Dhaka',
                'permanent_address' => 'Chandpur Sadar, Chandpur',
                'joining_date' => '2019-01-10',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-7.jpg',
                'speech' => 'We treat every single Taka as a sacred public trust (Amanah). Through strict auditing, zero-leakage fund tracking, and transparent reporting, we guarantee that your contributions directly uplift real human lives with the highest financial integrity.',
                'speech_tag' => "Treasurer's Financial Assurance",
                'bio' => 'Guarantees 100% itemized audit transparency, digital voucher verification, and real-time expense reconciliation.',
                'signature_text' => 'Engr. Shahadat Hossain',
                'signature_title' => 'Treasurer • Rotary Club of Shantinagar Dhaka',
                'badge_title' => 'Treasurer',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 4,
            ],

            // Board of Directors (BOD) Members
            [
                'employee_id' => 'EMP-005',
                'name' => 'Mohammad Anwarul Kabir',
                'designation' => 'Director (Relief Operations)',
                'phone' => '+8801715556677',
                'email' => 'anwar.bod@shantinagarfoundation.org',
                'nid_number' => '19752692550000005',
                'present_address' => 'Shanti Nagar, Dhaka',
                'permanent_address' => 'Comilla Sadar, Comilla',
                'joining_date' => '2019-06-01',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-8.jpg',
                'speech' => null,
                'speech_tag' => null,
                'bio' => 'Leads disaster relief supply chains and regional winter cloth distribution logistics.',
                'signature_text' => null,
                'signature_title' => null,
                'badge_title' => 'Director',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 5,
            ],
            [
                'employee_id' => 'EMP-006',
                'name' => 'Begum Rashida Akhtar',
                'designation' => 'Director (Social Welfare & Orphan Care)',
                'phone' => '+8801817778899',
                'email' => 'rashida.bod@shantinagarfoundation.org',
                'nid_number' => '19822692550000006',
                'present_address' => 'Eskaton Garden, Dhaka',
                'permanent_address' => 'Feni Sadar, Feni',
                'joining_date' => '2020-02-15',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-2.jpg',
                'speech' => null,
                'speech_tag' => null,
                'bio' => 'Directs educational kits, orphan sponsorship, and widow rehabilitation programs.',
                'signature_text' => null,
                'signature_title' => null,
                'badge_title' => 'Director',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 6,
            ],
            [
                'employee_id' => 'EMP-007',
                'name' => 'Dr. Tariqul Islam',
                'designation' => 'Director (Medical Aid & Healthcare)',
                'phone' => '+8801918889900',
                'email' => 'tariqul.bod@shantinagarfoundation.org',
                'nid_number' => '19842692550000007',
                'present_address' => 'Dhanmondi, Dhaka',
                'permanent_address' => 'Rangpur Sadar, Rangpur',
                'joining_date' => '2020-07-01',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-3.jpg',
                'speech' => null,
                'speech_tag' => null,
                'bio' => 'Manages free medical health camps, medicine procurement, and hospital aid.',
                'signature_text' => null,
                'signature_title' => null,
                'badge_title' => 'Director',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 7,
            ],
            [
                'employee_id' => 'EMP-008',
                'name' => 'Farhana Yasmin',
                'designation' => 'Director (Women Empowerment & Education)',
                'phone' => '+8801519990011',
                'email' => 'farhana.bod@shantinagarfoundation.org',
                'nid_number' => '19892692550000008',
                'present_address' => 'Shanti Nagar, Dhaka',
                'permanent_address' => 'Sylhet Sadar, Sylhet',
                'joining_date' => '2021-01-10',
                'base_salary' => 0.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-4.jpg',
                'speech' => null,
                'speech_tag' => null,
                'bio' => 'Facilitates sewing machine distribution, vocational training, and female literacy programs.',
                'signature_text' => null,
                'signature_title' => null,
                'badge_title' => 'Director',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 8,
            ],

            // Other Members / Field Coordinators
            [
                'employee_id' => 'EMP-101',
                'name' => 'Rafiqul Islam',
                'designation' => 'Field Project Coordinator',
                'phone' => '+8801712998877',
                'email' => 'rafiq.field@shantinagarfoundation.org',
                'nid_number' => '19882692550001234',
                'present_address' => 'House 14, Road 3, Shanti Nagar, Dhaka',
                'permanent_address' => 'Vill: Joypur, P.S: Nabinagar, Brahmanbaria',
                'joining_date' => '2023-01-15',
                'base_salary' => 35000.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-1.jpg',
                'speech' => null,
                'speech_tag' => null,
                'bio' => 'On-ground field supervisor for relief dispatch and project site assessment.',
                'signature_text' => null,
                'signature_title' => null,
                'badge_title' => 'Coordinator',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 9,
            ],
            [
                'employee_id' => 'EMP-102',
                'name' => 'Fatema Begum',
                'designation' => 'Accounts & Documentation Officer',
                'phone' => '+8801815667788',
                'email' => 'fatema.acc@shantinagarfoundation.org',
                'nid_number' => '19922692550005678',
                'present_address' => 'Malibagh Chowdhury Para, Dhaka',
                'permanent_address' => 'Vill: Chandpur Sadar, Chandpur',
                'joining_date' => '2023-06-01',
                'base_salary' => 30000.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-2.jpg',
                'speech' => null,
                'speech_tag' => null,
                'bio' => 'Manages ledger records, donor receipts, and monthly voucher reconciliation.',
                'signature_text' => null,
                'signature_title' => null,
                'badge_title' => 'Officer',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 10,
            ],
            [
                'employee_id' => 'EMP-103',
                'name' => 'Kamrul Hasan',
                'designation' => 'Volunteer Supervisor & Logistics Support',
                'phone' => '+8801914332211',
                'email' => 'kamrul.volunteer@shantinagarfoundation.org',
                'nid_number' => '19952692550009999',
                'present_address' => 'Santi Nagar Bazaar Lane, Dhaka',
                'permanent_address' => 'Vill: Shibpur, Narsingdi',
                'joining_date' => '2024-02-10',
                'base_salary' => 22000.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-3.jpg',
                'speech' => null,
                'speech_tag' => null,
                'bio' => 'Coordinates youth volunteer registration and emergency packing stations.',
                'signature_text' => null,
                'signature_title' => null,
                'badge_title' => 'Supervisor',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 11,
            ],
            [
                'employee_id' => 'EMP-104',
                'name' => 'Abdul Kader',
                'designation' => 'Office Caretaker & Logistics Assistant',
                'phone' => '+8801611009988',
                'email' => null,
                'nid_number' => '19792692550007777',
                'present_address' => 'Shanti Nagar Office Staff Room, Dhaka',
                'permanent_address' => 'Vill: Char Fasson, Bhola',
                'joining_date' => '2022-03-01',
                'base_salary' => 16000.00,
                'is_active' => true,
                'photo' => 'assets/images/team/team-4.jpg',
                'speech' => null,
                'speech_tag' => null,
                'bio' => 'Maintains the central Shanti Nagar foundation headquarters and warehouse inventory.',
                'signature_text' => null,
                'signature_title' => null,
                'badge_title' => 'Staff',
                'facebook_url' => 'https://facebook.com',
                'twitter_url' => 'https://twitter.com',
                'linkedin_url' => 'https://linkedin.com',
                'order_index' => 12,
            ],
        ];

        $allDesignations = Designation::pluck('id', 'name')->toArray();

        foreach ($employees as $employeeData) {
            $desigName = $employeeData['designation'] ?? null;
            if ($desigName && isset($allDesignations[$desigName])) {
                $employeeData['designation_id'] = $allDesignations[$desigName];
            }
            unset($employeeData['designation']);

            Employee::updateOrCreate(
                ['employee_id' => $employeeData['employee_id']],
                $employeeData
            );
        }
    }
}
