import re

def update_file(path, fn):
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    new_content = fn(content)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f"Updated {path}")

# 1. donation-details.blade.php
def transform_donation_details(content):
    c = content
    # Title
    c = c.replace("@section('title', $project->name . ' — Rotary Club of Shantinagar Dhaka')", "@section('title', $project->localized_name . ' — ' . site_setting('org_name', 'Rotary Club of Shantinagar Dhaka'))")
    c = c.replace("@section('meta_description', Str::limit($project->short_description ?: $project->description, 160))", "@section('meta_description', Str::limit($project->localized_short_description ?: $project->localized_description, 160))")
    c = c.replace("{{ $project->projectType->name }}", "{{ $project->projectType->localized_name }}")
    c = c.replace("<h1>{{ $project->name }}</h1>", "<h1>{{ $project->localized_name }}</h1>")
    c = c.replace("<li><a href=\"{{ route('home') }}\">Home</a></li>", "<li><a href=\"{{ route('home') }}\">{{ __('Home') }}</a></li>")
    c = c.replace("<li><a href=\"{{ route('donations') }}\">Projects & Causes</a></li>", "<li><a href=\"{{ route('donations') }}\">{{ __('Projects & Causes') }}</a></li>")
    c = c.replace("<li>{{ Str::limit($project->name, 35) }}</li>", "<li>{{ Str::limit($project->localized_name, 35) }}</li>")
    c = c.replace("<h5>Fund Raised</h5>", "<h5>{{ __('Fund Raised') }}</h5>")
    c = c.replace("৳{{ number_format($raised) }} <span>/ ৳{{ number_format($target) }}</span>", "৳{{ localized_number($raised) }} <span>/ ৳{{ localized_number($target) }}</span>")
    c = c.replace("<h5>{{ $percent }}%</h5>", "<h5>{{ localized_number($percent) }}%</h5>")
    c = c.replace("Donate Now</button>", "{{ __('Donate Now') }}</button>")
    c = c.replace("<h5>Location</h5>", "<h5>{{ __('Location') }}</h5>")
    c = c.replace("<p title=\"{{ $project->location }}\">{{ Str::limit($project->location, 16) }}</p>", "<p title=\"{{ $project->localized_location }}\">{{ Str::limit($project->localized_location ?: __('Dhaka, Bangladesh'), 16) }}</p>")
    c = c.replace("<h5>{{ $supportersCount }}+</h5>", "<h5>{{ localized_number($supportersCount) }}+</h5>")
    c = c.replace("<p>Supporters</p>", "<p>{{ __('Supporters') }}</p>")
    c = c.replace("<h5>Status</h5>", "<h5>{{ __('Project Status') }}</h5>")
    c = c.replace("<p>{{ ucfirst(str_replace('_', ' ', $project->status)) }}</p>", "<p>{{ __($project->status == 'completed' ? 'Completed' : ($project->status == 'in_progress' ? 'In Progress' : 'Planned')) }}</p>")
    c = c.replace("alt=\"{{ $project->name }}\"", "alt=\"{{ $project->localized_name }}\"")
    c = c.replace("<h3 class=\"project-heading\">{{ $project->name }}</h3>", "<h3 class=\"project-heading\">{{ $project->localized_name }}</h3>")
    c = c.replace("@if($project->short_description)\n                                        <p class=\"lead project-lead\">{{ $project->short_description }}</p>\n                                    @endif", "@if($project->localized_short_description)\n                                        <p class=\"lead project-lead\">{{ $project->localized_short_description }}</p>\n                                    @endif")
    c = c.replace("{!! nl2br(e($project->description ?: 'Rotary Club of Shantinagar Dhaka is dedicated to delivering transparent humanitarian relief, healthcare support, and social empowerment across Bangladesh. Every contribution directly funds verified on-the-ground initiatives without intermediaries.')) !!}", "{!! nl2br(e($project->localized_description ?: __('Rotary Club of Shantinagar Dhaka is dedicated to delivering transparent humanitarian relief, healthcare support, and social empowerment across Bangladesh. Every contribution directly funds verified on-the-ground initiatives without intermediaries.'))) !!}")
    c = c.replace("<h3 class=\"section-title-sub-2\">Field Documentation & Photos</h3>", "<h3 class=\"section-title-sub-2\">{{ __('Field Documentation') }}</h3>")
    c = c.replace("alt=\"{{ $img->caption ?: $project->name }}\"", "alt=\"{{ $img->localized_caption ?: $project->localized_name }}\"")
    c = c.replace("@if($img->caption)\n                                                    <p class=\"small text-muted mt-1\"><i class=\"fas fa-camera me-1 text-primary\"></i>\n                                                        {{ $img->caption }}</p>\n                                                @endif", "@if($img->localized_caption)\n                                                    <p class=\"small text-muted mt-1\"><i class=\"fas fa-camera me-1 text-primary\"></i>\n                                                        {{ $img->localized_caption }}</p>\n                                                @endif")
    c = c.replace("<h3 class=\"section-title-sub\">Make Your Contribution</h3>", "<h3 class=\"section-title-sub\">{{ __('Make Your Donation') }}</h3>")
    c = c.replace("Support <strong>{{ $project->name }}</strong> directly.", "{{ __('Support Our Humanity Causes') }}: <strong>{{ $project->localized_name }}</strong>.")
    c = c.replace("We ensure\n                                        100% financial transparency and official receipt vouchers.", "{{ __('Every single Taka you contribute reaches genuine underprivileged families across Bangladesh.') }}")
    c = c.replace("<h3>Select Amount (৳ BDT)</h3>", "<h3>{{ __('Select Contribution (BDT)') }}</h3>")
    c = c.replace("<label for=\"damt-500\" onclick=\"setDetailsAmount(500);\">৳ 500</label>", "<label for=\"damt-500\" onclick=\"setDetailsAmount(500);\">৳ {{ localized_number(500) }}</label>")
    c = c.replace("<label for=\"damt-1000\" onclick=\"setDetailsAmount(1000);\">৳ 1,000</label>", "<label for=\"damt-1000\" onclick=\"setDetailsAmount(1000);\">৳ {{ localized_number(1000) }}</label>")
    c = c.replace("<label for=\"damt-2500\" onclick=\"setDetailsAmount(2500);\">৳ 2,500</label>", "<label for=\"damt-2500\" onclick=\"setDetailsAmount(2500);\">৳ {{ localized_number(2500) }}</label>")
    c = c.replace("<label for=\"damt-5000\" onclick=\"setDetailsAmount(5000);\">৳ 5,000</label>", "<label for=\"damt-5000\" onclick=\"setDetailsAmount(5000);\">৳ {{ localized_number(5000) }}</label>")
    c = c.replace("<label for=\"damt-10000\" onclick=\"setDetailsAmount(10000);\">৳ 10,000</label>", "<label for=\"damt-10000\" onclick=\"setDetailsAmount(10000);\">৳ {{ localized_number(10000) }}</label>")
    c = c.replace("<label for=\"damt-25000\" onclick=\"setDetailsAmount(25000);\">৳ 25,000</label>", "<label for=\"damt-25000\" onclick=\"setDetailsAmount(25000);\">৳ {{ localized_number(25000) }}</label>")
    c = c.replace("<h4>Enter Custom Amount (৳)</h4>", "<h4>{{ __('Enter Custom Amount (৳)') }}</h4>")
    c = c.replace("<p>Enter any specific amount in BDT</p>", "<p>{{ __('Enter any specific amount in BDT') }}</p>")
    c = c.replace("<h3>Payment Method</h3>", "<h3>{{ __('Choose Payment Channel') }}</h3>")
    c = c.replace("<label for=\"pm_b\">bKash</label>", "<label for=\"pm_b\">{{ __('bKash') }}</label>")
    c = c.replace("<label for=\"pm_n\">Nagad</label>", "<label for=\"pm_n\">{{ __('Nagad') }}</label>")
    c = c.replace("<label for=\"pm_bank\">Bank Transfer</label>", "<label for=\"pm_bank\">{{ __('Bank Transfer') }}</label>")
    c = c.replace("<label for=\"pm_c\">Cash / Counter</label>", "<label for=\"pm_c\">{{ __('Cash / Direct') }}</label>")
    c = c.replace("<h3>Donor Information</h3>", "<h3>{{ __('Donor Information') }}</h3>")
    c = c.replace("<label>Your Name <span>*</span></label>", "<label>{{ __('Your Name') }} <span>*</span></label>")
    c = c.replace("<label>Email Address <span>*</span></label>", "<label>{{ __('Email Address') }} <span>*</span></label>")
    c = c.replace("<label>Phone / WhatsApp Number <span>*</span></label>", "<label>{{ __('Phone Number') }} <span>*</span></label>")
    c = c.replace("<label>Transaction ID / Reference (Optional)</label>", "<label>{{ __('Transaction ID / Reference') }}</label>")
    c = c.replace("<label>Address / District</label>", "<label>{{ __('Head Office') }} / {{ __('Location') }}</label>")
    c = c.replace("<label>Notes / Prayer Request (Optional)</label>", "<label>{{ __('Additional Notes / Dedication') }}</label>")
    c = c.replace("Complete\n                                                        Donation Pledge</button>", "{{ __('Complete Donation') }}</button>")
    c = c.replace("<h3 class=\"section-title-sub-2\">Recent Verified Contributors</h3>", "<h3 class=\"section-title-sub-2\">{{ __('Supporters') }}</h3>")
    c = c.replace("<h3>Other Active Causes</h3>", "<h3>{{ __('Active Relief Causes') }}</h3>")
    c = c.replace("{{ Str::limit($rp->name, 22) }}", "{{ Str::limit($rp->localized_name, 22) }}")
    c = c.replace("৳{{ number_format($rp->estimated_cost > 0 ? $rp->estimated_cost : 100000) }}", "৳{{ localized_number($rp->estimated_cost > 0 ? $rp->estimated_cost : 100000) }}")
    c = c.replace("<h3>Initiative Types</h3>", "<h3>{{ __('Relief Programs') }}</h3>")
    c = c.replace("{{ $type->name }}", "{{ $type->localized_name }}")
    c = c.replace("<span>{{ str_pad($type->projects_count, 2, '0', STR_PAD_LEFT) }}</span>", "<span>{{ localized_number($type->projects_count) }}</span>")
    c = c.replace("<h3>Need Assistance?</h3>", "<h3>{{ __('Need Assistance?') }}</h3>")
    c = c.replace("<p>For direct bank transfer confirmation or offline receipts, call our Dhaka desk.", "<p>{{ __('Have questions about donations, relief projects, or volunteering? Leave your details below and our team will contact you.') }}")
    c = c.replace("<h4 class=\"fw-bold text-dark mb-1 sidebar-help-phone\">+880 1700-000000</h4>", "<h4 class=\"fw-bold text-dark mb-1 sidebar-help-phone\">{{ site_setting('hotline', '+880 1711-000000') }}</h4>")
    c = c.replace("<p class=\"small text-muted mb-3\">House 14, Road 3, Shanti Nagar, Dhaka - 1217</p>", "<p class=\"small text-muted mb-3\">{{ site_setting('address', 'Shanti Nagar, Dhaka - 1217, Bangladesh') }}</p>")
    c = c.replace("Contact Foundation</a>", "{{ __('Contact Us') }}</a>")
    return c

update_file('/Users/zesan/Desktop/My-Work/shanti-nagar-foundation/resources/views/frontend/donation-details.blade.php', transform_donation_details)
